BEGIN TRY

BEGIN TRAN;

-- AddForeignKey
ALTER TABLE [dbo].[MapHeaderIssueFractionTAC] ADD CONSTRAINT [MapHeaderIssueFractionTAC_headerId_fkey] FOREIGN KEY ([headerId]) REFERENCES [dbo].[HeaderIssueTempTAC]([id]) ON DELETE NO ACTION ON UPDATE NO ACTION;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
